### ISSUE TITLE
Crew chief shouldn't have access to "Cancel" button for events

### ISSUE THREAD

**Issue by jtgiguere** [WPI-LNL/lnldb#330]
In the new interface, I noticed I had access to a "cancel" button. I believe I only have "Active" status, so I shouldn't be able to cancel events. If this privilege is intended, I suggest it be changed to a "Request to cancel," that requires an Officer or Administrator approval, or at least has a delay to allow for a reversal of the crew chief cancellation.

**Comment by jmerdich** [comment]
This is intentional, and events can be reopened if there is an accident.
The idea is that when an event is cancelled, eg. due to rain, the crew
chief is the first to know and the highest authority on the matter. It
would probably be a good idea for certain events to go through billing
after being cancelled if they have already set up, though.
