### ISSUE TITLE
Members training page is broken

### ISSUE THREAD

**Issue by rrlapointe** [WPI-LNL/lnldb#468]
This issue is a follow-up on the RT ticket that I opened for this issue 26 days ago. The members training page (https://lnl.wpi.edu/db/members/training/list/) doesn't work, as shown in the following screenshot:

![7809](https://user-images.githubusercontent.com/31218229/94833231-69690980-03fe-11eb-962e-2de13e8c6773.jpg)

Since I have some free time today, I spent about an hour to investigate the issue myself. The bug was introduced on Monday June 29 in commit d3e6d9066049e9872db321eeaccd86bf3e80b03e by @tnurse18. In that commit, @tnurse18 renamed the permission needed to see the members training page from `members.view_training` to `members.view_training_details` and then did not update the permissions of groups in production so groups don't have the new permission. I don't understand why this rename was needed, especially because `members.view_training` will still exists anyway since it is one of the "default" permissions in Django. In other words, a trivial and pointless change introduced a real and actual bug. The solution for this bug is to update the permissions of groups in production to add `members.view_training_details` to the groups that have `members.view_training`.

**Comment by tnurse18** [comment]
Thanks for catching that @rrlapointe. To clarify, this was actually changed in order to satisfy updates in newer versions of Django. While we have not yet made the jump to a newer version, I have been going through and trying to make the necessary changes now so that we do not need to later. In newer versions of Django you will actually get an error if `members.view_training` is defined like that. My solution for the time being was to rename the permissions defined in the models so that the code would work across multiple versions of Django at the same. Although now that I am looking back at it, it might just be easier to remove the `members.view_training_details` permission altogether as that may also do what we need.

**Comment by rrlapointe** [comment]
Oh, I see. If you remove the permission, then any logged-in user would be able to see the training page, including non-LNLers, right? That doesn't seem like a good idea.

**Comment by rrlapointe** [comment]
Or do you mean to change the permission required for the page back to `members.view_training` and remove only the definition in `members/models.py`? That makes sense

**Comment by tnurse18** [comment]
Well, the default Django permissions still exist in newer versions. I believe the difference is that they are created automatically for each model and therefore should not be defined again. Assuming we only assign that permission to the proper groups, it should be fine.

**Comment by tnurse18** [comment]
Yes, that is what I meant. Change the required permission back to `members.view_training` and remove the definition from `members/models.py`.

**Comment by rrlapointe** [comment]
Ok, that makes sense.

**Comment by rrlapointe** [comment]
The issue has been resolved.
